### ISSUE TITLE
Detect package.json in subfolders

### ISSUE THREAD

**Issue by RJiazhen** [elliotjharper/vscode-npm-script-run#2]
Hi, thanks for your extension, it is very useful for my development.

I also hope it supports detecting package.json scripts in subfolders, as shown in the npm scripts sidebar of vscode (below).
![image](https://github.com/user-attachments/assets/5a00a736-dcac-4fb5-8e84-970acfefd0e1)

And I am willing to participate in the development of this extension. If possible, I hope to talk about the future plans for this project.

**Comment by elliotjharper** [comment]
Hi, thanks for the interest in my little self helper tool.

That's an interesting idea.
Perhaps if we could conjure up a good idea for an equally simple UX workflow I'd knock something up.

My first thought for a v1 to get this to happen would be:
- Add an extra command palette entry like "Run NPM Script from Nested package.json"
- Pops up another drop down list of all the enumerated package.json files found so that you can type to search and generally use the keyboard to select the appropriate one.
- Then it continues, just as the original command does, to list the available scripts in this selected package json.

Then perhaps a v2 would be to adapt what happens after you launch the "Run NPM Script from nested package.json":
- Have the extension persist the last used nested package json and offer a pre highlighted "Last used: /src/lib-one/package.json" option amongst the list of located package json files to speed up re running.

What are your thoughts?

**Comment by RJiazhen** [comment]
> Hi, thanks for the interest in my little self helper tool.
> 
> That's an interesting idea. Perhaps if we could conjure up a good idea for an equally simple UX workflow I'd knock something up.
> 
> My first thought for a v1 to get this to happen would be:
> 
> * Add an extra command palette entry like "Run NPM Script from Nested package.json"
> * Pops up another drop down list of all the enumerated package.json files found so that you can type to search and generally use the keyboard to select the appropriate one.
> * Then it continues, just as the original command does, to list the available scripts in this selected package json.
> 
> Then perhaps a v2 would be to adapt what happens after you launch the "Run NPM Script from nested package.json":
> 
> * Have the extension persist the last used nested package json and offer a pre highlighted "Last used: /src/lib-one/package.json" option amongst the list of located package json files to speed up re running.
> 
> What are your thoughts?

I also hope this tool is simple and efficient enough to use, but my ideas are different.

I want to **show all npm scripts in drop-down list at once** after selecting the "Run NPM Script from Nested package.json".  The user can then continue to enter the path to packaga.json or the specific npm script content to find the special script (or just view all npm scripts in a specific package.json file).

Of course, in this drop-down list, the script used last time is displayed in the first position.

I think this allows users to execute the corresponding npm script faster when they know the specific npm script and the corresponding package.json file path. However, my idea may not be right. I will try to implement this function during this time to see if there is anything that needs improvement.

I also want to talk about the specific implementation and functions, I hope to try to **be consistent with the functions of the NPM SCRIPTS view of VScode**.

For example: 
- information on executable npm scripts and corresponding package.json files is obtained through VScode's api;
- executing npm scripts by running corresponding tasks (this may not be possible if run npm scripts on the current terminal).

This allows users who are accustomed to executing scripts through the NPM SCRIPTS view to adapt to the use of this extension more quickly, and even subconsciously closely associate the extension with VScode.

**Comment by elliotjharper** [comment]
One thing that I'll point out is that the vscode extensions api does not offer a built in functionality around package.json files and the scripts inside.

To list the scripts this extension tries to read package.json from the current workspace and parses the file itself.

So, to show all package.json files this extension would probably have to do some sort of glob search for "**/package.json" to find them.

This is also why I propose selecting a file and then listing the scripts.
Otherwise the extension will have to go and find all package.json files and parse the contents of all of them.
This is a lot more heavy handed.

So I still think in terms of project plan / achievable goals (as a side project) a v1 should be a two step.
Then perhaps a v2 where it finds all package.json files, parses them, hashes them and then the extension remembers that for your workspace.
That would mean that on successive executions it could just compare to the hash of files for speed.

**Comment by RJiazhen** [comment]
Yes, you are right. VScode does not provide an api to retrieve all npm scripts. It is implemented through a built-in npm [extension](https://github.com/microsoft/vscode/blob/main/extensions/npm/src/npmMain.ts), but the npm extension does not provide an api to access the npm script data it generates.

So I refered to this built-in extension to detect and run npm screipts in subfolders, and listened for changes in package.json to regenerate the npm script list. And the implementation of pinning the last run script at the top.

However, the current execution performance of watching package.jsonmay not be the best. There is no loading status remainder when update script list, and it can be optimized later.

The following is the demonstration effect.

https://github.com/user-attachments/assets/717701b5-a51d-4a49-91f6-9346eb14b7e0
